# Generated by Django 3.2.9 on 2021-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
